#!/bin/bash

# Programed by Scourge
# Licence: GPLv3

route=$(echo all)
if (( $# == 2 )); then
    route=$(echo one)
elif (( $# == 0 )); then
    echo "ifs '<someting to search for in files>'"
    echo "searches every file in the tree"
    echo
    echo "ifs  <someting to search for in files> <target file>" 
    echo "searches only the target file"
    echo
    exit
fi

char_limit=1000        # <<<<<<<<<<< set char limit

term_leng=$(stty size| cut -d' ' -f2 ) # same as (tput cols)
echo;printf "%0.s=" $(seq 1 $term_leng);echo # print = in range 1 to
$term_length
printf "%0.s-" $(seq 1 $term_leng);echo


function looper 
{

    # grep -IinE --color=auto $1 $file
    # -I =  --binary-files=without-match
    # -i =  ignore case distinctions
    # -n =  print line number with output lines
    # -E =  Expressions

    if [ $test_fail -eq 0 ]; then
        file_size=$(ls -l "$file" | awk -F ' ' '{print $5}')

        if [ "$file_size" -le 7000000 ];then
            # get line by line grepable content

            content=$(grep -RIinE --color=auto $1 $file)
            # -I =  --binary-files=without-match
            # -i =  ignore case distinctions
            # -n =  print line number with output lines
            # -E =  Expressions

            if [ "${#content}" -lt "$char_limit" ] && [ "${#content}" -gt 12 ];then
                printf "%0.s-" $(seq 1 $term_leng)
                echo -e "\e[33m"
                echo "  >>> $file <<<"
                grep -IinE --color=auto $1 $file

            fi
        else
            echo "The File is too big: $file"
        fi
    fi

}

if [ "$route" == "all" ];then
    for file in $(find ./ -type f );do
        # 1st test action and silence input, 2nd if the action succeeds, runthe script
        ls -l "$file" > /dev/null 2>&1
        test_fail=$?
        looper $1 $file
    done
else
    file=$(echo $2 )
    ls -l "$file" > /dev/null 2>&1
    test_fail=$?
    looper $1 $file
fi
printf "%0.s-" $(seq 1 $term_leng);echo
printf "%0.s=" $(seq 1 $term_leng);echo;echo # print = in range 1 to
$term_length
