#!/bin/bash

# Programed by Scourge
# Licence: GPLv3

route=$(echo all)
if (( $# == 2 )); then
    route=$(echo one)
elif (( $# == "$1" )); then
    echo "avs '<someting to search for in files>'"
    exit
fi

char_limit=1000        # <<<<<<<<<<< set char limit

term_leng=$(stty size| cut -d' ' -f2 ) # same as (tput cols)
echo;printf "%0.s=" $(seq 1 $term_leng);echo # print = in range 1 to $term_length
printf "%0.s-" $(seq 1 $term_leng) && echo


function looper 
{
    if [ $test_fail -eq 0 ]; then

        file_size=$(ls -l "$file" | awk -F ' ' '{print $5}')
        if [ "$file_size" -le 7000000 ];then
            # get line by line grepable content
            file=$(echo $file | sed 's/zgfialaiavneil/\ /g; s/(/\\(/g; s/)/\\)/g')

            grepped=$(grep -inI "$1" "$file" --color --no-messages )
            one_line_grepped=$(echo $grepped \
            | sed 's/^/ajoeaivamnlisa/g; s/\.\//ajoeaivamnlisa/g' \
            | sed 's/\s/_/g; s/ajoeaivamnlisa/\n/g')


            pass=1
            for line in "$one_line_grepped";do
                if [ "${#line}" -gt "$char_limit" ] && [ "${#line}" -le 12 ];then
                    pass=0
                    break
                fi
            done
            if [ "$pass" -eq 1 ];then
                grep -inI --no-messages "$1" "$file" --color /dev/null && printf "%0.s-" $(seq 1 $term_leng) && echo
            else
                echo "Chars Off: $file"
            fi
        fi
    fi

}

if [ "$route" == "all" ];then
    for file in $(find ./ -type f );do
        # 1st test action and silence input, 2nd if the action succeeds, run the script
        ls -l "$file" > /dev/null 2>&1
        test_fail=$?
        looper $1 $file
    done
else
    file=$(echo $2)
    ls -l "$file" > /dev/null 2>&1
    test_fail=$?
    looper $1 $file
fi

printf "%0.s=" $(seq 1 $term_leng);echo;echo # print = in range 1 to $term_length
